### ISSUE TITLE
generate-all is mentioned, but does not exist

### ISSUE THREAD

**Issue by stefan-jung** [oasis-open/dita-rng-converter#10]
The `<target name="help">` mentions the `generate-all` target, but it does not exist.

**Comment by nakohdo** [comment]
The target is available in the development branch:

```xml
<target name="generate-all" 
    description="Generates all shells and modules for both DTD and XSD syntax"
    depends="init, clean, generate-dtd, generate-xsd-url, generate-xsd-urn, generate-catalogs"
>
```
https://github.com/oasis-open/dita-rng-converter/blob/develop/build.xml

**Comment by nakohdo** [comment]
The target is also available in @ToshihikoMakita's [pull request](https://github.com/ToshihikoMakita/dita-rng-converter/blob/0f72d0ba730e7e1e0fa0c9bd15de4c3bcbe77556/build.xml) even if it strangly doesn't show up in the [diff](https://github.com/oasis-open/dita-rng-converter/pull/3/files#diff-2cccd7bf48b7a9cc113ff564acd802a8).

**Comment by drmacro** [comment]
Target is available on develop branch.
