### ISSUE TITLE
Naming conventions?

### ISSUE THREAD

**Issue by nakohdo** [oasis-open/dita-rng-converter#12]
None of our domain contraints like _par_highlightDomainConstraint.rng_ got converted. After renaming the file to _par_highlightDomainConstraint**Mod**.rng_ the conversion works.

Are there any other naming conventions regarding the file naming we must keep in mind? Is this documentend somewhere?

Best regards,
Frank

**Comment by nakohdo** [comment]
I've faced a similar issue with .ent files not being generated for topic constraint modules like, for example, _par_conceptConstraintMod.rng_.

In this case I had to change the module type from  `<moduleType>constraint</moduleType>` to `<moduleType>topic</moduleType>` to make the conversion work.

**Comment by nakohdo** [comment]
@drmacro 

I think the underlying problem we are struggling with is as follows:


For topics, there are basically three module types:

| \<moduleType> | \<moduleShortName> | example RNG                 | generated DTD |
|----------------------|-------------------------------|------------------------------------|----------------------|
| topicshell          | concept                        | concept.rng                       | concept.dtd      |
|                            | par_concept                | par_concept.rng               | par_concept.dtd |
| topic                  | concept                        | conceptMod.rng              | concept.mod |
|                            |        | *no parson equivalent*   |  *missing for parson customization*   |
| constraint         | strictTaskbody            | strictTaskbodyConstraintMod.rng | strictTaskbodyConstraint.mod |
|                         | par_concept-c                | par_conceptConstraintMod.rng |  par_conceptConstraint.mod |

For our customization, we are only using a shell and a constraint file. So it looks as if some of the required entries that go into the DTD .mod file are missing in our generated DTD files.

### Questions  

1. Is the problem analysed correctly?
2. Can we fix this in the source RNG files: file name, \<moduleType> or \<moduleShortName>?
3. Do we have to adapt the XSLT scripts?

Any pointer welcome.

Best regards,
Frank

**Comment by drmacro** [comment]
The naming conventions used in the OASIS-supplied modules are just that, conventions. However, the current RNG-to-DITA code depends on those conventions.

I reviewed the 1.3 RNG coding conventions and we didn't codify those naming conventions and if we had they would at most be SHOULD, not MUST (the TC has been moving away from trying to require specific names for files as part of the spec).

I'll review the code that depends on naming conventions and replace it where possible.

But as a workaround, you should use "Mod.rng" for all module files. That's probably a good practice regardless (that is, naming conventions are good thing and we strongly urge their use even if they are not, technically, required).

**Comment by drmacro** [comment]
I've corrected the rngfunc:isModuleDoc() function to use the module type defined in the module metadata, not the RNG filename, to determine if a module is or is not a module of some type.

Produces the correct result using the ah-dita RNG, which does not follow the OASIS naming convention.

Pushed to develop branch.
