### ISSUE TITLE
"generate-all" does not exist

### ISSUE THREAD

**Issue by stefan-jung** [oasis-open/dita-rng-converter#19]
Hi @drmacro, 

The [build.xml, line 161](https://github.com/oasis-open/dita-rng-converter/blob/ec41097b0b1135e756755379331415a503fdb4a7/build.xml#L161) contains: 

```
[generate-all|generate-dtd|generate-catalogs]
```

But "generate-all" does not exist. This is confusing me.

**Comment by kirkilj** [comment]
@xephon2 , did you ever get an answer to this question?

**Comment by stefan-jung** [comment]
Hi @kirkilj, I don't think so.

**Comment by stefan-jung** [comment]
But actually it's [there](https://github.com/oasis-open/dita-rng-converter/blob/562b255b4848e14c2770f1811c9f6e2e14922e71/build.xml#L206) (now?), so I'm closing this.
